## create user

POST http://localhost:7000/api/auth/register
content-type: application/json

{
  "name": "JohnDoe",
  "email": "pitacix602@bitofee.com",
  "password": "password123",
  "age": 25

}


########## Get users 
GET http://localhost:5000/v1/users
content-type: application/json


######### ADD message
POST http://localhost:5000/v1/messages
content-type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY1YTAzOGZmYWZiYWRjNDhmYTY1M2Y1NiIsIm5hbWUiOiJKb2huRG9lIiwiZW1haWwiOiJjYWZpdmUzczEzMkB0YWxtZXRyeS5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRSWldqS3hBdFlMRXNUbWxTS0ZuTmdPdmpNSE9RMXV6dGU0SHQ1T0tjSjNDaU9tOEdTSThoSyIsImFnZSI6MjUsInZlcmlmaWVkIjpmYWxzZSwiaXNBY3RpdmUiOnRydWUsInJvbGUiOiJ1c2VyIiwiY3JlYXRlZEF0IjoiMjAyNC0wMS0xMVQxODo1Mjo0Ny4zMDBaIiwidXBkYXRlZEF0IjoiMjAyNC0wMS0xMVQxODo1Mjo0Ny4zMDBaIiwiX192IjowfSwiaWF0IjoxNzA1MDAxMDMxLCJleHAiOjE3MDUwMDQ2MzF9.HzArRZYZ_SWT5LoBF6cplEG61is766jyauDQ7sRDdGY

{
  "message": "Hello World",
  "receviedId": "5f9b3b3b9b9b9b9b9b9b9b9b"
  

}

#### login
POST http://localhost:7000/api/auth/login
content-type: application/json

{
   "email": "pitacix602@bitofee.com",
  "password": "password123"
}


#### update user
PATCH http://localhost:5000/v1/user/659d525f0fe31c066c396476
content-type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY1OWQ1MjVmMGZlMzFjMDY2YzM5NjQ3NiIsIm5hbWUiOiJKb2huRG9lIiwiZW1haWwiOiJjYWZpdmUzMTMyQHRhbG1ldHJ5LmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJDFsZi94VVlnb2d1N0Y4M1dMZjhiUmV4VjFqenJrdHVwczd0U1o1MmRhcUZDaXU1cFdOQ0hXIiwiYWdlIjoyNSwidmVyaWZpZWQiOmZhbHNlLCJpc0FjdGl2ZSI6dHJ1ZSwiY3JlYXRlZEF0IjoiMjAyNC0wMS0wOVQxNDowNDoxNS4zNzNaIiwidXBkYXRlZEF0IjoiMjAyNC0wMS0wOVQxNDowNDoxNS4zNzNaIiwiX192IjowfSwiaWF0IjoxNzA0ODE2NTQ2LCJleHAiOjE3MDQ4MjAxNDZ9.nv98JGZ30WJVQkZxOVISf_2wV07NZJHSV2c_J1hJKao

{
  "name": "JohnDoe",
  "email": ""
}


#### Update message
PATCH http://localhost:5000/v1/messages/65a042969044b6d9ad4e7807
content-type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY1YTAzOGZmYWZiYWRjNDhmYTY1M2Y1NiIsIm5hbWUiOiJKb2huRG9lIiwiZW1haWwiOiJjYWZpdmUzczEzMkB0YWxtZXRyeS5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRSWldqS3hBdFlMRXNUbWxTS0ZuTmdPdmpNSE9RMXV6dGU0SHQ1T0tjSjNDaU9tOEdTSThoSyIsImFnZSI6MjUsInZlcmlmaWVkIjpmYWxzZSwiaXNBY3RpdmUiOnRydWUsInJvbGUiOiJ1c2VyIiwiY3JlYXRlZEF0IjoiMjAyNC0wMS0xMVQxODo1Mjo0Ny4zMDBaIiwidXBkYXRlZEF0IjoiMjAyNC0wMS0xMVQxODo1Mjo0Ny4zMDBaIiwiX192IjowfSwiaWF0IjoxNzA1MDAxMDMxLCJleHAiOjE3MDUwMDQ2MzF9.HzArRZYZ_SWT5LoBF6cplEG61is766jyauDQ7sRDdGY

{
  "message": "Hello Worlsssd"
}

#### Post Photo

POST http://localhost:7000/api/users/profile/profile-Photo/65af6cd816eb48c99d22c3ec
Content-Disposition: form-data; name="image"; filename="1.png"
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YjU0YzJhZjQ3NTVjZjU4Y2FiMzBlZiIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3MDYzODA1MTMsImV4cCI6MTcwNjM4NDExM30.LQTGC5YOo0izvFENl08YZ5up1V3l19vhCSd5ISyj9B4
Content-Type: image/png

### count users

GET http://localhost:7000/api/users/count
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YjU0YzJhZjQ3NTVjZjU4Y2FiMzBlZiIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3MDYzODA1MTMsImV4cCI6MTcwNjM4NDExM30.LQTGC5YOo0izvFENl08YZ5up1V3l19vhCSd5ISyj9B4